language: go

before_script:
  - wget https://github.com/spf13/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
  - tar -xvf /tmp/hugo.tar.gz
  - export PATH=$PATH:$PWD/hugo_0.21_Linux-64bit/

before_install:
  - go get github.com/mitchellh/gox

go:
  - 1.7
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: tlrgMjV53nADbIWwdBYuPcom6reWMDnF3h8dmLC0uzrtlXg8QCAVFoDE+QJIlpW/DHhJrWBUDW5tc+6EUZul4XMNAFWWu9OWizUsFdkiA/Hg4sf3ju8FTlqyJNe4XUdnCIrNVYaG0yxxoFdi1RHfuyTOY9cE/em3z/lp64sRRy+/mex8UXEId/BnvxvEc9ReLO6l1fuMTopRQ6JKml6kVlEFFQk5Fx8n2Cn5u2QnQkaQdoIZrLzGyB4Oy6b6YB5tQTl8RJTeOO5EP5qqNvf/joISogRMIafXea1o+H7coUoEdtvIWjDyygn3PmroCE7RKd3OrilApARDOT79fX8gMgAk0HWJHBF9GLumXO7CJtH0coOfJ7kcVfLffm5Fye6vaXcyrIB7Fzdv1re/z/C9Hpg+85N8eldbnmzQ1R8fRJgCCPzlJEFgr7GhJ0Ry4Fz0jRlGkJyT6Ic9rhSilxsVmHV3Wr+XiM6WzREUeO/OlA7knn2OWVnL0QGNptpDtFUntPD6Vovs+Ces4y/g58ggwYL+NkMO6d4xyXLDltu42WtBWySlAWSJhB/dT/Q5MRjLLzIJ7dCz5PpVqlzfgcIkeFo/m/TrcPHS84EUEXPNQx5kxnfw2VpJIPNChc2KuU1KSdk6nig5VVXtBF5iE+8UnEg1WV4B385UfUF1x5gfOts=
  file_glob: true
  file:
    - "dist/edward_${TRAVIS_TAG}_linux_386.zip"
    - "dist/edward_${TRAVIS_TAG}_linux_amd64.zip"
    - "dist/edward_${TRAVIS_TAG}_macOS_64bit.zip"
  on:
    repo: yext/edward
    tags: true
