baseurl = "http://engblog.yext.com/edward/"
languageCode = "en-us"
title = "Edward Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir = "../docs"

[params]
	# General information
	author = "Tom Elliott"
	description = "A command line tool for managing local instances of microservices."
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/yext/edward"

	version = "1.8.1"
	#logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "indigo"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "yext"
	email   = "telliott@yext.com"


[[menu.main]]
	name   = "About Edward"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Installation"
	url    = "installation/"
	weight = 10

[[menu.main]]
	name   = "Quickstart"
	url    = "quickstart/"
	weight = 20

[[menu.main]]
  name   = "Commands"
  url    = "commands/"
  weight = 30

[[menu.main]]
  name   = "Project Configuration"
  url    = "projectconfig/"
  weight = 40

[[menu.main]]
  name   = "Autocompletion"
	url    = "autocompletion/"
	weight = 50

[[menu.main]]
	name   = "Sudo"
	url    = "sudo/"
	weight = 60

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 70

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 80


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
